name: Build and publish package

on:
  schedule:
    - cron: "0 12 * * 3"
  workflow_dispatch:

jobs:
  build_publish:
    name: "Build"
    runs-on: docker
    container:
      image: archlinux:latest
      options: --privileged
      env:
        DOCKER_HOST: "tcp://docker:2375"
        DOCKER_TLS_CERTDIR: ""
    services:
        docker:
          image: docker:28.3.1-dind
          options: --privileged -- dockerd -H tcp://0.0.0.0:2375 --tls=false
          env:
            DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Install deps
        run: pacman --noconfirm -Sy git nodejs curl docker docker-buildx

      - name: Wait until dockerd ready
        run: sleep 5

      - name: Check Docker service logs
        run: curl -s docker:2375/version || echo "dockerd might have failed"

      - name: Docker check
        run: docker info

      - uses: actions/checkout@v4

      - name: Login to the registry
        run: docker login -u Land -p ${{ secrets.CODEBERG_TOKEN }} codeberg.org
        # uses: docker/login-action@v3
        # with:
        #   registry: codeberg.org
        #   username: Land
        #   password: ${{ secrets.CODEBERG_TOKEN }}
          
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build
        run: cd docker && docker build -t codeberg.org/land/tempsystem .
        # uses: docker/build-push-action@v6
        # with:
        #   context: docker
        #   push: true
        #   provenance: false
        #   platforms: linux/amd64
        #   tags: codeberg.org/land/tempsystem:latest

      - name: Push
        run: cd docker && docker push codeberg.org/land/tempsystem