name: Docker image build

on:
  push:
    branches: [ "master" ]
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  build:
    name: "Build Image"
    runs-on: docker
    container:
      image: archlinux:latest
    steps:
      - name: Login to Codeberg
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: Land
          password: ${{ secrets.CODEBERG_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: land/tempsystem