export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="gentoo"

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
	fzf
	sudo
	archlinux
)

if [ -e "$ZSH/oh-my-zsh.sh" ]; then
	source $ZSH/oh-my-zsh.sh
fi

export TERM=xterm-256color
figlet Welcome | lolcat